/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PlayerJump:String = "event:/SFX/Player/Jump/PlayerJump";
    public static inline var PlayerLand:String = "event:/SFX/Player/Land/PlayerLand";
    public static inline var PlayerStep:String = "event:/SFX/Player/Step/PlayerStep";
    public static inline var ShipCrash:String = "event:/SFX/Ship/ShipCrash";
    public static inline var ShipExplode:String = "event:/SFX/Ship/ShipExplode";
    public static inline var ShipExplodeMini:String = "event:/SFX/Ship/ShipExplodeMini";
    public static inline var ShipFall:String = "event:/SFX/Ship/ShipFall";
    public static inline var VoicePrepareYourself:String = "event:/SFX/Voice/VoicePrepareYourself";
    public static inline var WeaponGunShoot:String = "event:/SFX/Weapons/WeaponGunShoot";
}
